export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_PRODUCT = "DELETE_PRODUCT ";
export const CALCULATE_ORDER_SUM = "CALCULATE_ORDER_SUM";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const CONFIRM_DELETE = "CONFIRM_DELETE";
export const SET_PRODUCTS_ITEMS = "SET_PRODUCTS_ITEMS";
